### ISSUE TITLE
Error: Cannot find module 'json5'

### ISSUE THREAD

**Issue by siiron** [salesforce-ux/theo#77]
5.0.0-beta.6 gives me the following error when running gulp:

```
Error: Cannot find module 'json5'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Username\Projects\Projectname\node_modules\theo\dist\props\index.js:28:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by kaelig** [comment]
Thank you for pointing this out. Let me clean up the dependencies and release a new beta.

**Comment by kaelig** [comment]
It should be fixed in https://github.com/salesforce-ux/theo/releases/tag/v5.0.0-beta.7

Thanks again @siiron!
